// The KDigital v1.2 Final Programme and Course Registry, as data.
//
// Generated from
//   docs/KDigital Platform v1.2 Final Programme and Course Registry.xlsx
//   (sheets: Programs, Courses, Programme Components, 10 Catalogue Rules)
// and then checked in, deliberately. CAT-001 says these identifiers are
// permanent — a permanent identifier belongs under version control where a
// change to it shows up in a diff and a review, not in a spreadsheet cell
// somebody edits between imports. `seed-catalogue.ts` is the only reader.
//
// Do not hand-edit. Re-generate from a newer registry workbook, and expect
// the diff to be reviewed: an ID that MOVES here is a breaking change to
// every certificate and credit decision already resolved by it.
//
// Contents: 9 programmes, 52 courses, 72 effective-dated components.

export type CatalogueStatus = "Draft" | "Published" | "Retired";

export interface RegistryProgramme {
  registryId: string;          // K-P003-FSAE — permanent (CAT-001)
  sequence: number;
  shortCode: string;           // FSAE (CAT-011)
  name: string;                // official display name — never silently renamed (CAT-010)
  fullName: string;
  searchAlias: string;         // normalised spelling, search only (CAT-004)
  programmeType: string;
  family: string;
  description: string;
  credentialType: string;
  deliveryModes: string[];
  catalogueVersion: string;
  catalogueStatus: CatalogueStatus;
  effectiveFrom: string | null;
  effectiveTo: string | null;
}

export interface RegistryCourse {
  registryId: string;          // K-C008-PYTH
  sequence: number;
  shortCode: string;
  name: string;
  searchAlias: string;
  family: string;
  description: string;
  reusableAcrossProgrammes: boolean;  // CAT-002
  independentlyDeliverable: boolean;
  credentialType: string;
  curriculumVersionPattern: string;   // CAT-015
  catalogueVersion: string;
  catalogueStatus: CatalogueStatus;
  effectiveFrom: string | null;
  effectiveTo: string | null;
}

export interface RegistryComponent {
  programmeId: string;                 // parent programme registry id
  sequenceNumber: number;              // 1-based in the registry; stored as rank = n - 1
  componentType: "Course" | "Programme";
  componentReferenceId: string;        // course OR programme registry id (CAT-007)
  componentRole: string;
  specialisationGroup: string | null;  // CAT-008
  required: boolean;
  creditReuseAllowed: boolean;         // CAT-003
  catalogueVersion: string;
  catalogueStatus: "Active" | "Retired";
  effectiveFrom: string | null;
  effectiveTo: string | null;
}

// Governance rules that travel with the registry. Carried here so the naming
// and identifier constraints the seeder relies on are readable next to the
// data they constrain, rather than only in the workbook.
export interface CatalogueRule {
  ruleId: string;
  category: string;
  rule: string;
  recommendation: string;
  status: string;
  example: string;
}

export const REGISTRY_CATALOGUE_VERSION = "2026.08";

export const REGISTRY_PROGRAMMES: RegistryProgramme[] = [
  { registryId: "K-P001-BAAI", sequence: 1, shortCode: "BAAI", name: "Business Analyst with GenAI & Agentic AI", fullName: "Business Analyst with GenAI & Agentic AI", searchAlias: "Business Analyst with GenAI and Agentic AI", programmeType: "Career Pathway", family: "Business Analysis", description: "Official KDigital Business Analyst with GenAI & Agentic AI career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P002-AIPO", sequence: 2, shortCode: "AIPO", name: "AI Product Owner", fullName: "AI Product Owner", searchAlias: "AI Product Owner", programmeType: "Career Pathway", family: "Product Leadership", description: "Official KDigital AI Product Owner career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P003-FSAE", sequence: 3, shortCode: "FSAE", name: "Full Stack AI Application Engineering", fullName: "Full Stack AI Application Engineering", searchAlias: "Full Stack AI Application Engineering", programmeType: "Career Pathway", family: "Application Engineering", description: "Official KDigital Full Stack AI Application Engineering career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P004-DAIO", sequence: 4, shortCode: "DAIO", name: "DevOps & AI Operations", fullName: "DevOps & AI Operations: MLOps, LLMOps and AgentOps", searchAlias: "DevOps and AI Operations", programmeType: "Career Pathway", family: "DevOps and AI Operations", description: "Official KDigital DevOps & AI Operations career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P005-QENG", sequence: 5, shortCode: "QENG", name: "Quality Engineering", fullName: "Quality Engineering: Software Testing and AI Evaluation", searchAlias: "Quality Engineering", programmeType: "Career Pathway", family: "Quality Engineering", description: "Official KDigital Quality Engineering career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P006-DENG", sequence: 6, shortCode: "DENG", name: "Data Engineering", fullName: "Data Engineering", searchAlias: "Data Engineering", programmeType: "Career Pathway", family: "Data Engineering", description: "Official KDigital Data Engineering career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P007-AAIE", sequence: 7, shortCode: "AAIE", name: "Applied AI Engineer", fullName: "Applied AI Engineer", searchAlias: "Applied AI Engineer", programmeType: "Career Pathway", family: "Applied AI", description: "Official KDigital Applied AI Engineer career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P008-FDE", sequence: 8, shortCode: "FDE", name: "Forward Deployed AI Engineer", fullName: "Forward Deployed AI Engineer", searchAlias: "Forward Deployed AI Engineer", programmeType: "Composite Career Pathway", family: "Forward Deployment", description: "Official KDigital Forward Deployed AI Engineer career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-P009-SNOW", sequence: 9, shortCode: "SNOW", name: "ServiceNow Platform Engineering", fullName: "ServiceNow Platform Engineering", searchAlias: "ServiceNow Platform Engineering", programmeType: "Career Pathway", family: "ServiceNow", description: "Official KDigital ServiceNow Platform Engineering career pathway.", credentialType: "Programme Certificate", deliveryModes: ["Online", "Classroom", "Hybrid"], catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
];

export const REGISTRY_COURSES: RegistryCourse[] = [
  { registryId: "K-C001-FAAI", sequence: 1, shortCode: "FAAI", name: "Fundamentals of Applications, Agile and AI", searchAlias: "Fundamentals of Applications, Agile and AI", family: "Foundation", description: "Official reusable KDigital learning unit: Fundamentals of Applications, Agile and AI.", reusableAcrossProgrammes: true, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C001-FAAI-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C002-MBA", sequence: 2, shortCode: "MBA", name: "Modern Business Analyst with GenAI and Agentic AI", searchAlias: "Modern Business Analyst with GenAI and Agentic AI", family: "Business and Product", description: "Official reusable KDigital learning unit: Modern Business Analyst with GenAI and Agentic AI.", reusableAcrossProgrammes: true, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C002-MBA-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C003-AIPO", sequence: 3, shortCode: "AIPO", name: "AI Product Ownership and Platform Leadership", searchAlias: "AI Product Ownership and Platform Leadership", family: "Business and Product", description: "Official reusable KDigital learning unit: AI Product Ownership and Platform Leadership.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C003-AIPO-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C004-WEBF", sequence: 4, shortCode: "WEBF", name: "Web Foundations: HTML, CSS, JavaScript and TypeScript", searchAlias: "Web Foundations: HTML, CSS, JavaScript and TypeScript", family: "Application Engineering", description: "Official reusable KDigital learning unit: Web Foundations: HTML, CSS, JavaScript and TypeScript.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C004-WEBF-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C005-REACT", sequence: 5, shortCode: "REACT", name: "Modern Enterprise Frontend Applications with React", searchAlias: "Modern Enterprise Frontend Applications with React", family: "Application Engineering", description: "Official reusable KDigital learning unit: Modern Enterprise Frontend Applications with React.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C005-REACT-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C006-NODE", sequence: 6, shortCode: "NODE", name: "Backend Engineering with Node.js, Express and MongoDB", searchAlias: "Backend Engineering with Node.js, Express and MongoDB", family: "Application Engineering", description: "Official reusable KDigital learning unit: Backend Engineering with Node.js, Express and MongoDB.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C006-NODE-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C007-SQLDB", sequence: 7, shortCode: "SQLDB", name: "SQL and Relational Database Foundations", searchAlias: "SQL and Relational Database Foundations", family: "Application Engineering", description: "Official reusable KDigital learning unit: SQL and Relational Database Foundations.", reusableAcrossProgrammes: true, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C007-SQLDB-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C008-PYTH", sequence: 8, shortCode: "PYTH", name: "Python Programming", searchAlias: "Python Programming", family: "Application Engineering", description: "Official reusable KDigital learning unit: Python Programming.", reusableAcrossProgrammes: true, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C008-PYTH-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C009-FAPI", sequence: 9, shortCode: "FAPI", name: "API Development with FastAPI", searchAlias: "API Development with FastAPI", family: "Application Engineering", description: "Official reusable KDigital learning unit: API Development with FastAPI.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C009-FAPI-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C010-EINT", sequence: 10, shortCode: "EINT", name: "Enterprise Application Integration", searchAlias: "Enterprise Application Integration", family: "Application Engineering", description: "Official reusable KDigital learning unit: Enterprise Application Integration.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C010-EINT-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C011-AIAI", sequence: 11, shortCode: "AIAI", name: "AI Application Integration", searchAlias: "AI Application Integration", family: "Application Engineering", description: "Official reusable KDigital learning unit: AI Application Integration.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C011-AIAI-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C012-DEVOPS", sequence: 12, shortCode: "DEVOPS", name: "Core DevOps Engineering", searchAlias: "Core DevOps Engineering", family: "DevOps and AI Operations", description: "Official reusable KDigital learning unit: Core DevOps Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C012-DEVOPS-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C013-AWS", sequence: 13, shortCode: "AWS", name: "AWS Cloud Computing", searchAlias: "AWS Cloud Computing", family: "DevOps and AI Operations", description: "Official reusable KDigital learning unit: AWS Cloud Computing.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C013-AWS-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C014-AZURE", sequence: 14, shortCode: "AZURE", name: "Microsoft Azure Cloud Foundations", searchAlias: "Microsoft Azure Cloud Foundations", family: "DevOps and AI Operations", description: "Official reusable KDigital learning unit: Microsoft Azure Cloud Foundations.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C014-AZURE-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C015-AIOPS", sequence: 15, shortCode: "AIOPS", name: "AI Operations: MLOps, LLMOps and AgentOps", searchAlias: "AI Operations: MLOps, LLMOps and AgentOps", family: "DevOps and AI Operations", description: "Official reusable KDigital learning unit: AI Operations: MLOps, LLMOps and AgentOps.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C015-AIOPS-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C016-MTEST", sequence: 16, shortCode: "MTEST", name: "Manual Software Testing", searchAlias: "Manual Software Testing", family: "Quality Engineering", description: "Official reusable KDigital learning unit: Manual Software Testing.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C016-MTEST-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C017-ATEST", sequence: 17, shortCode: "ATEST", name: "Test Automation Engineering", searchAlias: "Test Automation Engineering", family: "Quality Engineering", description: "Official reusable KDigital learning unit: Test Automation Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C017-ATEST-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C018-APIT", sequence: 18, shortCode: "APIT", name: "API and Integration Testing", searchAlias: "API and Integration Testing", family: "Quality Engineering", description: "Official reusable KDigital learning unit: API and Integration Testing.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C018-APIT-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C019-TAI", sequence: 19, shortCode: "TAI", name: "Software Testing with AI", searchAlias: "Software Testing with AI", family: "Quality Engineering", description: "Official reusable KDigital learning unit: Software Testing with AI.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C019-TAI-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C020-AIEVAL", sequence: 20, shortCode: "AIEVAL", name: "GenAI, RAG and Agentic AI Testing and Evaluation", searchAlias: "GenAI, RAG and Agentic AI Testing and Evaluation", family: "Quality Engineering", description: "Official reusable KDigital learning unit: GenAI, RAG and Agentic AI Testing and Evaluation.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C020-AIEVAL-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C021-PSGT", sequence: 21, shortCode: "PSGT", name: "Performance, Security and Governance Testing", searchAlias: "Performance, Security and Governance Testing", family: "Quality Engineering", description: "Official reusable KDigital learning unit: Performance, Security and Governance Testing.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C021-PSGT-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C022-PBI", sequence: 22, shortCode: "PBI", name: "Data Analytics with Microsoft Power BI", searchAlias: "Data Analytics with Microsoft Power BI", family: "Data Engineering", description: "Official reusable KDigital learning unit: Data Analytics with Microsoft Power BI.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C022-PBI-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C023-PYSP", sequence: 23, shortCode: "PYSP", name: "PySpark for Data Engineering", searchAlias: "PySpark for Data Engineering", family: "Data Engineering", description: "Official reusable KDigital learning unit: PySpark for Data Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C023-PYSP-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C024-PIPE", sequence: 24, shortCode: "PIPE", name: "Production Data Pipeline Engineering", searchAlias: "Production Data Pipeline Engineering", family: "Data Engineering", description: "Official reusable KDigital learning unit: Production Data Pipeline Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C024-PIPE-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C025-DEAIX", sequence: 25, shortCode: "DEAIX", name: "Data Engineering for Physical AI, GenAI and Agentic AI", searchAlias: "Data Engineering for Physical AI, GenAI and Agentic AI", family: "Data Engineering", description: "Official reusable KDigital learning unit: Data Engineering for Physical AI, GenAI and Agentic AI.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C025-DEAIX-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C026-DBX", sequence: 26, shortCode: "DBX", name: "Databricks Data Engineering", searchAlias: "Databricks Data Engineering", family: "Data Engineering", description: "Official reusable KDigital learning unit: Databricks Data Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C026-DBX-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C027-MSFAB", sequence: 27, shortCode: "MSFAB", name: "Microsoft Fabric Data Engineering", searchAlias: "Microsoft Fabric Data Engineering", family: "Data Engineering", description: "Official reusable KDigital learning unit: Microsoft Fabric Data Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C027-MSFAB-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C028-MSTAT", sequence: 28, shortCode: "MSTAT", name: "Mathematics, Probability and Statistics for AI", searchAlias: "Mathematics, Probability and Statistics for AI", family: "Applied AI", description: "Official reusable KDigital learning unit: Mathematics, Probability and Statistics for AI.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C028-MSTAT-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C029-PYLIB", sequence: 29, shortCode: "PYLIB", name: "Python Libraries for Data Science and AI", searchAlias: "Python Libraries for Data Science and AI", family: "Applied AI", description: "Official reusable KDigital learning unit: Python Libraries for Data Science and AI.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C029-PYLIB-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C030-MLDL", sequence: 30, shortCode: "MLDL", name: "Machine Learning, Deep Learning and Natural Language Processing", searchAlias: "Machine Learning, Deep Learning and Natural Language Processing", family: "Applied AI", description: "Official reusable KDigital learning unit: Machine Learning, Deep Learning and Natural Language Processing.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C030-MLDL-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C031-GENAI", sequence: 31, shortCode: "GENAI", name: "Generative AI Engineering", searchAlias: "Generative AI Engineering", family: "Applied AI", description: "Official reusable KDigital learning unit: Generative AI Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C031-GENAI-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C032-AGENT", sequence: 32, shortCode: "AGENT", name: "Agentic AI and Production AI Systems", searchAlias: "Agentic AI and Production AI Systems", family: "Applied AI", description: "Official reusable KDigital learning unit: Agentic AI and Production AI Systems.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C032-AGENT-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C033-SNFND", sequence: 33, shortCode: "SNFND", name: "ServiceNow Platform Foundations", searchAlias: "ServiceNow Platform Foundations", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Platform Foundations.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C033-SNFND-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C034-SNADM", sequence: 34, shortCode: "SNADM", name: "ServiceNow Administration and ITSM", searchAlias: "ServiceNow Administration and ITSM", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Administration and ITSM.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C034-SNADM-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C035-SNDEV", sequence: 35, shortCode: "SNDEV", name: "ServiceNow Development Foundations: HTML, CSS and JavaScript", searchAlias: "ServiceNow Development Foundations: HTML, CSS and JavaScript", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Development Foundations: HTML, CSS and JavaScript.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C035-SNDEV-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C036-SNSCR", sequence: 36, shortCode: "SNSCR", name: "ServiceNow Scripting and Application Development", searchAlias: "ServiceNow Scripting and Application Development", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Scripting and Application Development.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C036-SNSCR-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C037-SNWS", sequence: 37, shortCode: "SNWS", name: "ServiceNow Workspaces and User Experiences", searchAlias: "ServiceNow Workspaces and User Experiences", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Workspaces and User Experiences.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C037-SNWS-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C038-SNINT", sequence: 38, shortCode: "SNINT", name: "ServiceNow Integrations", searchAlias: "ServiceNow Integrations", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Integrations.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C038-SNINT-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C039-SNAI", sequence: 39, shortCode: "SNAI", name: "ServiceNow AI, Now Assist and AI Agents", searchAlias: "ServiceNow AI, Now Assist and AI Agents", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow AI, Now Assist and AI Agents.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C039-SNAI-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C040-HRSD", sequence: 40, shortCode: "HRSD", name: "ServiceNow HR Service Delivery", searchAlias: "ServiceNow HR Service Delivery", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow HR Service Delivery.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C040-HRSD-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C041-ITOM", sequence: 41, shortCode: "ITOM", name: "ServiceNow IT Operations Management", searchAlias: "ServiceNow IT Operations Management", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow IT Operations Management.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C041-ITOM-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C042-CSM", sequence: 42, shortCode: "CSM", name: "ServiceNow Customer Service Management", searchAlias: "ServiceNow Customer Service Management", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Customer Service Management.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C042-CSM-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C043-SPM", sequence: 43, shortCode: "SPM", name: "ServiceNow Strategic Portfolio Management", searchAlias: "ServiceNow Strategic Portfolio Management", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Strategic Portfolio Management.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C043-SPM-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C044-ITAM", sequence: 44, shortCode: "ITAM", name: "ServiceNow IT Asset Management", searchAlias: "ServiceNow IT Asset Management", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow IT Asset Management.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C044-ITAM-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C045-SNCRM", sequence: 45, shortCode: "SNCRM", name: "ServiceNow Sales CRM", searchAlias: "ServiceNow Sales CRM", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Sales CRM.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C045-SNCRM-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C046-IRM", sequence: 46, shortCode: "IRM", name: "ServiceNow Integrated Risk Management", searchAlias: "ServiceNow Integrated Risk Management", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Integrated Risk Management.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C046-IRM-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C047-FDDQ", sequence: 47, shortCode: "FDDQ", name: "Forward Deployment Discovery and Opportunity Qualification", searchAlias: "Forward Deployment Discovery and Opportunity Qualification", family: "Forward Deployment", description: "Official reusable KDigital learning unit: Forward Deployment Discovery and Opportunity Qualification.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C047-FDDQ-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C048-FDSD", sequence: 48, shortCode: "FDSD", name: "Enterprise AI Solution Design and Deployment", searchAlias: "Enterprise AI Solution Design and Deployment", family: "Forward Deployment", description: "Official reusable KDigital learning unit: Enterprise AI Solution Design and Deployment.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C048-FDSD-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C049-FDCH", sequence: 49, shortCode: "FDCH", name: "Stakeholder Enablement and Change Management", searchAlias: "Stakeholder Enablement and Change Management", family: "Forward Deployment", description: "Official reusable KDigital learning unit: Stakeholder Enablement and Change Management.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C049-FDCH-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C050-FDPR", sequence: 50, shortCode: "FDPR", name: "Forward Deployment Practicum and Customer Residency", searchAlias: "Forward Deployment Practicum and Customer Residency", family: "Forward Deployment", description: "Official reusable KDigital learning unit: Forward Deployment Practicum and Customer Residency.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C050-FDPR-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C051-SNCMDB", sequence: 51, shortCode: "SNCMDB", name: "ServiceNow CMDB and Common Service Data Model", searchAlias: "ServiceNow CMDB and Common Service Data Model", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow CMDB and Common Service Data Model.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C051-SNCMDB-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
  { registryId: "K-C052-SNTEST", sequence: 52, shortCode: "SNTEST", name: "ServiceNow Testing and Quality Engineering", searchAlias: "ServiceNow Testing and Quality Engineering", family: "ServiceNow", description: "Official reusable KDigital learning unit: ServiceNow Testing and Quality Engineering.", reusableAcrossProgrammes: false, independentlyDeliverable: true, credentialType: "Course Certificate", curriculumVersionPattern: "K-C052-SNTEST-VYYYY.N", catalogueVersion: "2026.08", catalogueStatus: "Published", effectiveFrom: "2026-08-01", effectiveTo: null },
];

export const REGISTRY_COMPONENTS: RegistryComponent[] = [
  { programmeId: "K-P001-BAAI", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P001-BAAI", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C002-MBA", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P002-AIPO", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P002-AIPO", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C002-MBA", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P002-AIPO", sequenceNumber: 3, componentType: "Course", componentReferenceId: "K-C003-AIPO", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C004-WEBF", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 3, componentType: "Course", componentReferenceId: "K-C005-REACT", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 4, componentType: "Course", componentReferenceId: "K-C006-NODE", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 5, componentType: "Course", componentReferenceId: "K-C007-SQLDB", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 6, componentType: "Course", componentReferenceId: "K-C008-PYTH", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 7, componentType: "Course", componentReferenceId: "K-C009-FAPI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 8, componentType: "Course", componentReferenceId: "K-C010-EINT", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P003-FSAE", sequenceNumber: 9, componentType: "Course", componentReferenceId: "K-C011-AIAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P004-DAIO", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P004-DAIO", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C012-DEVOPS", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P004-DAIO", sequenceNumber: 3, componentType: "Course", componentReferenceId: "K-C013-AWS", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P004-DAIO", sequenceNumber: 4, componentType: "Course", componentReferenceId: "K-C014-AZURE", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P004-DAIO", sequenceNumber: 5, componentType: "Course", componentReferenceId: "K-C015-AIOPS", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P005-QENG", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P005-QENG", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C016-MTEST", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P005-QENG", sequenceNumber: 3, componentType: "Course", componentReferenceId: "K-C017-ATEST", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P005-QENG", sequenceNumber: 4, componentType: "Course", componentReferenceId: "K-C018-APIT", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P005-QENG", sequenceNumber: 5, componentType: "Course", componentReferenceId: "K-C019-TAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P005-QENG", sequenceNumber: 6, componentType: "Course", componentReferenceId: "K-C020-AIEVAL", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P005-QENG", sequenceNumber: 7, componentType: "Course", componentReferenceId: "K-C021-PSGT", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C008-PYTH", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 3, componentType: "Course", componentReferenceId: "K-C007-SQLDB", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 4, componentType: "Course", componentReferenceId: "K-C022-PBI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 5, componentType: "Course", componentReferenceId: "K-C023-PYSP", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 6, componentType: "Course", componentReferenceId: "K-C024-PIPE", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 7, componentType: "Course", componentReferenceId: "K-C025-DEAIX", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 8, componentType: "Course", componentReferenceId: "K-C026-DBX", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P006-DENG", sequenceNumber: 9, componentType: "Course", componentReferenceId: "K-C027-MSFAB", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C008-PYTH", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 3, componentType: "Course", componentReferenceId: "K-C007-SQLDB", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 4, componentType: "Course", componentReferenceId: "K-C028-MSTAT", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 5, componentType: "Course", componentReferenceId: "K-C029-PYLIB", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 6, componentType: "Course", componentReferenceId: "K-C030-MLDL", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 7, componentType: "Course", componentReferenceId: "K-C031-GENAI", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P007-AAIE", sequenceNumber: 8, componentType: "Course", componentReferenceId: "K-C032-AGENT", componentRole: "Core Course", specialisationGroup: null, required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Foundation Course", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 2, componentType: "Programme", componentReferenceId: "K-P001-BAAI", componentRole: "Referenced Pathway", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 3, componentType: "Programme", componentReferenceId: "K-P003-FSAE", componentRole: "Referenced Pathway", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 4, componentType: "Programme", componentReferenceId: "K-P004-DAIO", componentRole: "Referenced Pathway", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 5, componentType: "Programme", componentReferenceId: "K-P005-QENG", componentRole: "Referenced Pathway", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 6, componentType: "Programme", componentReferenceId: "K-P006-DENG", componentRole: "Referenced Pathway", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 7, componentType: "Programme", componentReferenceId: "K-P007-AAIE", componentRole: "Referenced Pathway", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 8, componentType: "Programme", componentReferenceId: "K-P002-AIPO", componentRole: "Referenced Pathway", specialisationGroup: "Composite FDE Pathway", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 9, componentType: "Course", componentReferenceId: "K-C047-FDDQ", componentRole: "FDE-Specific Course", specialisationGroup: "Forward Deployment", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 10, componentType: "Course", componentReferenceId: "K-C048-FDSD", componentRole: "FDE-Specific Course", specialisationGroup: "Forward Deployment", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 11, componentType: "Course", componentReferenceId: "K-C049-FDCH", componentRole: "FDE-Specific Course", specialisationGroup: "Forward Deployment", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P008-FDE", sequenceNumber: 12, componentType: "Course", componentReferenceId: "K-C050-FDPR", componentRole: "FDE-Specific Course", specialisationGroup: "Forward Deployment", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 1, componentType: "Course", componentReferenceId: "K-C001-FAAI", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 2, componentType: "Course", componentReferenceId: "K-C033-SNFND", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 3, componentType: "Course", componentReferenceId: "K-C034-SNADM", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 4, componentType: "Course", componentReferenceId: "K-C035-SNDEV", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 5, componentType: "Course", componentReferenceId: "K-C051-SNCMDB", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 6, componentType: "Course", componentReferenceId: "K-C036-SNSCR", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 7, componentType: "Course", componentReferenceId: "K-C037-SNWS", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 8, componentType: "Course", componentReferenceId: "K-C038-SNINT", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 9, componentType: "Course", componentReferenceId: "K-C052-SNTEST", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 10, componentType: "Course", componentReferenceId: "K-C039-SNAI", componentRole: "Core Course", specialisationGroup: "ServiceNow Core Platform", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 11, componentType: "Course", componentReferenceId: "K-C040-HRSD", componentRole: "Product Specialisation", specialisationGroup: "ServiceNow Product Specialisation", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 12, componentType: "Course", componentReferenceId: "K-C041-ITOM", componentRole: "Product Specialisation", specialisationGroup: "ServiceNow Product Specialisation", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 13, componentType: "Course", componentReferenceId: "K-C042-CSM", componentRole: "Product Specialisation", specialisationGroup: "ServiceNow Product Specialisation", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 14, componentType: "Course", componentReferenceId: "K-C043-SPM", componentRole: "Product Specialisation", specialisationGroup: "ServiceNow Product Specialisation", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 15, componentType: "Course", componentReferenceId: "K-C044-ITAM", componentRole: "Product Specialisation", specialisationGroup: "ServiceNow Product Specialisation", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 16, componentType: "Course", componentReferenceId: "K-C045-SNCRM", componentRole: "Product Specialisation", specialisationGroup: "ServiceNow Product Specialisation", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
  { programmeId: "K-P009-SNOW", sequenceNumber: 17, componentType: "Course", componentReferenceId: "K-C046-IRM", componentRole: "Product Specialisation", specialisationGroup: "ServiceNow Product Specialisation", required: true, creditReuseAllowed: true, catalogueVersion: "2026.08", catalogueStatus: "Active", effectiveFrom: "2026-08-01", effectiveTo: null },
];

export const CATALOGUE_RULES: CatalogueRule[] = [
  { ruleId: "CAT-001", category: "Identifier", rule: "Programme and course IDs are permanent.", recommendation: "Never recycle or mutate an issued ID.", status: "Adopted", example: "K-P003-FSAE / K-C008-PYTH" },
  { ruleId: "CAT-002", category: "Reuse", rule: "Reusable courses retain the same ID across programmes.", recommendation: "Resolve credit by Course ID, not by course-name text.", status: "Adopted", example: "K-C001-FAAI" },
  { ruleId: "CAT-003", category: "Credit", rule: "Completed shared courses may be credited across pathways.", recommendation: "Keep completion evidence and curriculum-version compatibility.", status: "Adopted", example: "Shared foundation credit" },
  { ruleId: "CAT-004", category: "Naming", rule: "Names may be refined without changing established IDs.", recommendation: "Store prior names as searchable aliases and effective-dated history.", status: "Adopted", example: "programme_name + search_alias" },
  { ruleId: "CAT-005", category: "Programme", rule: "Programme IDs identify complete career pathways.", recommendation: "Use programme IDs for enrolment, cohort and programme certificates.", status: "Adopted", example: "K-P007-AAIE" },
  { ruleId: "CAT-006", category: "Course", rule: "Course IDs identify independently deliverable learning units.", recommendation: "Use course IDs for assignments, credit and course certificates.", status: "Adopted", example: "K-C031-GENAI" },
  { ruleId: "CAT-007", category: "Composite", rule: "FDE references existing programmes rather than duplicating courses.", recommendation: "Represent programme references through Programme Components.", status: "Adopted", example: "K-P008-FDE → K-P003-FSAE" },
  { ruleId: "CAT-008", category: "Specialisation", rule: "ServiceNow product areas follow the core platform pathway.", recommendation: "Use specialisation_group instead of creating duplicate core courses.", status: "Adopted", example: "ServiceNow Product Specialisation" },
  { ruleId: "CAT-009", category: "Structure", rule: "Programme, course, module, cohort and certificate records share catalogue conventions.", recommendation: "Validate identifiers at API and import boundaries.", status: "Adopted", example: "K-C008-PYTH-M01" },
  { ruleId: "CAT-010", category: "Display name", rule: "Official names remain exactly as approved in the supplied registry.", recommendation: "Use search_alias for normalized 'and' spelling; do not silently rename the official record.", status: "Recommended", example: "DevOps & AI Operations" },
  { ruleId: "CAT-011", category: "Short code", rule: "The mnemonic suffix is uppercase and immutable after issue.", recommendation: "Restrict to 3–6 A–Z/0–9 characters and avoid technology-version numbers.", status: "Recommended", example: "FSAE / AIPO / SNOW" },
  { ruleId: "CAT-012", category: "Module ID", rule: "Modules extend the permanent course ID.", recommendation: "Use two-digit sequence suffixes and keep version outside the stable module ID.", status: "Recommended", example: "K-C008-PYTH-M01" },
  { ruleId: "CAT-013", category: "Cohort ID", rule: "Cohorts must be distinguishable from programme master IDs.", recommendation: "Prefer an explicit COH token while retaining the programme ID.", status: "Recommended", example: "K-COH-P003-FSAE-2027-01" },
  { ruleId: "CAT-014", category: "Certificate ID", rule: "Certificate IDs should identify credential scope and source pathway.", recommendation: "Include P or C scope plus the full mnemonic before year and sequence.", status: "Recommended", example: "K-CERT-P003-FSAE-2027-0001" },
  { ruleId: "CAT-015", category: "Versioning", rule: "Stable catalogue IDs are separate from curriculum versions.", recommendation: "Use effective dates plus an explicit curriculum version such as V2026.1.", status: "Recommended", example: "K-C008-PYTH-V2026.1" },
];
